const StudentActionType = {
  FETCH_ALL_STUDENTS: "FETCH_ALL_STUDENTS",
  FETCH_STUDENT_BY_ID: "FETCH_STUDENT_BY_ID",
  ADD_STUDENT: "ADD_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
};

export default StudentActionType;
