const CampusActionType = {
  FETCH_ALL_CAMPUSES: "FETCH_ALL_CAMPUSES",
  FETCH_CAMPUS_BY_ID: "FETCH_CAMPUS_BY_ID",
  ADD_CAMPUS: "ADD_CAMPUS",
  UPDATE_CAMPUS: "UPDATE_CAMPUS",
  DELETE_CAMPUS: "DELETE_CAMPUS",
};

export default CampusActionType;
